title: Bottles
description: Easily run Windows software on Linux with 🍷 Bottles!
author: Bottles Developers
email: mail@usebottles.com
logo: /uploads/logo.svg?v4

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

navigation_left:
    - link: "/appstore/"
      name: Apps
    - link: "/database/"
      name: Database
    - link: "/blog/"
      name: Blog
    - link: "https://forum.usebottles.com"
      name: Forums
    - link: "/funding/"
      name: Funding
navigation_right:
    - link: "/blog/LAS-2022/"
      name: "<b>@LAS22</b>"
      place: right
    - link: "https://docs.usebottles.com/"
      name: <ion-icon name="book-outline"></ion-icon> Docs
      place: right
    - link: "https://github.com/bottlesdevs/Bottles/issues/new/choose"
      name: <ion-icon name="bug-outline"></ion-icon> Bug report
      place: right
    - link: "https://hosted.weblate.org/engage/bottles/"
      name: <ion-icon name="language-outline"></ion-icon> Help translating
      place: right

url: "https://usebottles.com"
plugins:
  - jekyll-feed
  - jekyll-sitemap
